included: # paths to include during linting. `--path` is ignored if present.
    - Sources
excluded:
    - "Sources/ResponseManager+addRoutes.swift"
    - Sources/HTTPHeaders.swift
line_length:
    - 120 # warning
    - 160 # error

