defaults: &defaults
  docker:
    - image: klembara/swift4:0.0.1
    - image: mongo:3.4.4

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Build
          command: |
           swift package resolve
           swift package update
           swift build
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/
            - Package.resolved

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            swift test --parallel

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build