defaults: &defaults
  docker:
    - image: klembara/swift4:0.0.1
    - image: mongo:3.4.4

version: 2.0
jobs:
  resolve:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
            - build-cache-{{ .Branch }}
            - build-cache
      - run:
          name: Resolve
          command: |
           swift package resolve
           swift package update
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "Package.swift" }}
          paths:
            - .build/
            - Package.resolved

  build_debug:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build for debug
          command: swift build

  build_release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build for release
          command: swift build

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: swift test --parallel

workflows:
  version: 2
  resolve_build_test:
    jobs:
      - resolve
      - build_debug:
          requires:
            - resolve
      - build_release:
          requires:
            - resolve
      - test:
          requires:
            - build_debug
            - build_release